(require 'diminish)

(diminish 'smartparens-mode)
(diminish 'undo-tree-mode)
(diminish 'company-mode)
(diminish 'smooth-scroll-mode)
(diminish 'emmet-mode)
(diminish 'global-whitespace-mode)
(diminish 'auto-revert-mode)
(diminish 'rainbow-mode)
(diminish 'flyspell-mode)
(diminish 'helm-mode)
(diminish 'smooth-scroll-mode)
(diminish 'which-key-mode)
(diminish 'smart-tab-mode)
(diminish 'eldoc-mode)
(diminish 'yas-minor-mode)
